### ISSUE TITLE
关于子条目复用错乱的问题

### ISSUE THREAD

**Issue by JGNS** [Sky0202/About_BRVAH#1]
我的是二级列表，但是第二级列表中有个动态显示下载进度的textview，这样就必须的刷新条目了，然后我看的是demo中注释掉的方案，  getData().set(helper.getLayoutPosition(), sectionEntity); notifyDataSetChanged(); 确实出现了bug，就是整个二级条目的数据显示成了别的一级条目的二级数据，或者同一级下面有相同的二级数据，不知道大佬解决没？求回复！

**Comment by Sky0202** [comment]
二级的 setTag 试一下

**Comment by JGNS** [comment]
多谢回复，偶然试出来了， if (helper.getLayoutPosition() > 0) {
                                            sectionEntity.DownRate = uniqueLocal.DownRate;
                                            notifyDataSetChanged();
                                        }
直接给属性赋值，然后notifyDataSetChanged，暂时没啥问题。
